#######################################################################################
# Book settings
title                         : Data Science Notes Template
author                        : Jubayer Hossain
logo                          : 'logo.png'
email                         : jubayer@hdrobd.org
description: >-
  Template for writing data science notes or books

execute:
  execute_notebooks           : cache


html:
  favicon                     : 'favicon.png'
  home_page_in_navbar         : false
  use_edit_page_button        : true
  use_repository_button       : true
  use_issue_button            : true


repository:
  url                         : https://github.com/hossainlab/dsn-template/
  branch                      : master
  path_to_book                : book


# launch_buttons:
  # notebook_interface          : classic
  # binderhub_url               : "https://mybinder.org"
  # colab_url                   : "https://colab.research.google.com"
  # thebe                       : true
